bundle:
  name: adls_bronze_pipeline

targets:
  dev:
    workspace:
      host: https://dbc-ac974108-f7a7.cloud.databricks.com/?o=7474656457621483

    variables:
      catalog_name: dev
      schema_name: 00_landing_zone

resources:
  volumes:
    customer_volume:
      name: 01_managed_volume
      catalog_name: ${var.catalog_name}
      schema_name: ${var.schema_name}

    sales_volume:
      name: 02_managed_volume
      catalog_name: ${var.catalog_name}
      schema_name: ${var.schema_name}

  jobs: {}
  pipelines: {}
