env: dev

storage:
  customers_path: "/Volumes/dev/00_landing_zone/01_managed_volume"
  sales_path: "/Volumes/dev/00_landing_zone/02_managed_volume"

tables:
  bronze_customers: dev_bronze_customers
  bronze_sales: dev_bronze_sales

format:
  input: csv
  output: delta

options:
  header: true
  inferSchema: true
