variables:
  catalog: prod  # Production üçün fərqli kataloq
  schema_landing: 00_landing_zone
  schema_bronze: bronze
  schema_silver: silver
  schema_gold: gold

  customer_volume: /Volumes/prod/00_landing_zone/01_managed_volume
  sales_volume: /Volumes/prod/00_landing_zone/02_managed_volume
