name: Databricks CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Test Databricks API Connection
        run: |
          curl -X GET https://${{ secrets.DATABRICKS_HOST }}/api/2.0/clusters/list \
          -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}"
