name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main # v0.2.1 yerinə stabil 'main' istifadə edək

      - name: Deploy Bundle
        run: databricks bundle deploy -t prod
        env:
          DATABRICKS_HOST: https://dbc-ac974108-f7a7.cloud.databricks.com
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
